variables:
  KUBERNETES_CPU_REQUEST: 2
  RUNNER_REQUEST_CONCURRENCY: 2 # I think KUBERNETES_CPU_REQUEST x RUNNER_REQUEST_CONCURRENCY should be less than 8
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_MEMORY_REQUEST: 4Gi

  # DOCKER_TLS_CERTDIR: "/certs"
  # DOCKER_TLS_VERIFY: 1
  # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
      - yarn.lock

  paths:
    - cache/Cypress
    - .yarn/cache
    - build

stages:
  - build
  - test

build:
  stage: build
  image: docker:cli
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    # wait for docker service to be ready
    - i=0; while [ "$i" -lt 12 ]; do docker info >/dev/null && break; sleep 5; i=$(( i + 1 )) ; done
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f docker/e2e.Dockerfile -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $TEST == null
      changes: # I don't see this working?
        - docker/e2e.Dockerfile
        - yarn.lock

.tests:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  before_script:
    - yarn install --immutable
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"


  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

include: .gitlab/generated/tests.yml

command:
  extends: .tests
  script:
    - eval $CY_COMMAND
  rules:
    - if: $TEST == "command"
