#!/usr/bin/env node

const {isProgramRunning, getPid} = require('./shared/daemon.js')

if(isProgramRunning('serve')) {
  try {
    process.kill(getPid('serve', 2))
    console.log('Sent SIGINT to dev server')
  } catch(e) {
    console.error(e)
  }
} else {
  console.log('Dev server is not running')
}

if(isProgramRunning('apollo')) {
  try {
    process.kill(getPid('apollo', 2))
    console.log('Sent SIGINT to apollo')
  } catch(e) {
    console.error(e)
  }
} else {
  console.log('Apollo is not running')
}
