name: Cypress CI

on: [push]
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Install cypress dependencies
      #   run: sudo apt-get update --fix-missing && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Install yarn dependencies
        run: npm i -g yarn && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: Run unit tests
        run: yarn test
      - name: Compile
        run: yarn build --mode dev
      # - name: Update Unfurl
      #   run: pip3 install -U  "git+https://github.com/onecommons/unfurl.git#egg=unfurl"
      # - name: Run apollo and serve
      #   run: UNFURL_MOCK_DEPLOY='true' yarn start
      # - name: Run Cypress
      #   run: xargs yarn run cypress run -C cypress-ci.json -s  < cypress/ci-tests.txt
      # - name: Archive test screenshots
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: screenshots
      #     path: |
      #       cypress/screenshots/
      # - name: Archive test videos
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: videos
      #     path: |
      #       cypress/videos/


